name: {NAME}
vendor: Jon Seymour <jon@ninjablocks.com>
architecture: [armhf]
version: {VERSION}
icon: meta/{NAME}.svg
services:
 - name: {NAME}
   description: "Sphere Zigbee ZStack Gateway"
   start: ./{NAME}
integration:
  {NAME}:
    apparmor-profile: meta/{NAME}.profile
ports:
  required: 2533, 2536, 2540, 2541, 2525

