name: sphere-wireless
vendor: Mark Wolfe <mark.wolfe@ninjablocks.com>
architecture: [armhf]
version: 2.0.2-33
icon: meta/sphere-wireless.svg
services:
 - name: sphere-wireless
   description: "Sphere Wireless Configuration"
   start: ./ninja-shim ./sphere-wireless
integration:
  sphere-led-controller:
    apparmor-profile: meta/sphere-wireless.profile
