name: ninjasphere
vendor: Theo Julienne <theo@ninjablocks.com>
architecture: [amd64, armhf]
version: 0.0.12
type: framework
icon: meta/ninjasphere.svg
services:
 - name: mosquitto
   description: "Mosquitto MQTT Broker"
   start: ./bin/mosquitto -c ./etc/mosquitto.conf
 - name: redis-server
   description: "Redis Server"
   start: ./bin/redis-server-wrap
 - name: sphere-client
   description: "Ninja Sphere Client"
   start: ./bin/sphere-client-wrap
 - name: mqtt-bridgeify
   description: "Ninja Sphere Cloud MQTT Bridge"
   start: ./bin/mqtt-bridgeify-wrap
 - name: enable-gadget-serial
   description: "Enable the USB serial gadget"
   start: ./bin/enable-gadget-serial
binaries:
 - name: ./bin/redis-cli
 - name: ./bin/pub
 - name: ./bin/sub
 - name: ./bin/sphere-serial
 - name: ./bin/sphere-config
 - name: ./bin/sphere-installation
ports:
  required: 8000,1883,6379
integration:
  framework:
    framework: meta/ninjasphere.framework
  mqtt-bridgeify:
    apparmor-profile: meta/mqtt-bridgeify.profile
  sphere-client:
    apparmor-profile: meta/sphere-client.profile
  mosquitto:
    apparmor: meta/ninjasphere.apparmor
  redis-server:
    apparmor: meta/ninjasphere.apparmor
  sphere-serial:
    apparmor-profile: meta/sphere-serial.profile
  enable-gadget-serial:
    apparmor-profile: meta/enable-gadget-serial.profile
